CC = g++
CFLAGS = -I . -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal    \
         -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs         \
         -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe             \
         -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body            \
         -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op                    \
         -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual           \
         -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing                 \
         -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG         \
         -D_EJUDGE_CLIENT_SIDE                                                             \

BUILDDIR = build

SOURCES = main.cpp                             \
		  stack.cpp                             \

INCLUDES = stack.h                            \

OBJECTS = $(patsubst %.cpp,$(BUILDDIR)/%.o,$(SOURCES))

EXECUTABLE = cat

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

$(BUILDDIR)/%.o: %.cpp
	@if not exist "$(dir $@)" mkdir "$(dir $@)"
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILDDIR) $(EXECUTABLE)
